force-app/main/default/objects/Account/fields/Multiple_Payments_Failed__c.field-meta.xml
<CustomField>
    <fullName>Multiple_Payments_Failed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box if there are multiple payments failed for am account.</description>
    <label>Multiple Payments Failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumberOfFailedPayments__c.field-meta.xml
<CustomField>
    <fullName>NumberOfFailedPayments__c</fullName>
    <description>Total failed payments on an account</description>
    <inlineHelpText>Auto calculated based on total number of failure payments attempts in Payment for an account</inlineHelpText>
    <label>NumberOfFailedPayments</label>
    <summaryFilterItems>
        <field>Payment__c.Status__c</field>
        <operation>equals</operation>
        <value>failure</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment__c.Employer1__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/FailedPaymentInfo__mdt/FailedPaymentInfo__mdt.object-meta.xml
<CustomObject>
    <label>FailedPaymentInfo</label>
    <pluralLabel>FailedPaymentsInfo</pluralLabel>
</CustomObject>

force-app/main/default/classes/MultiplePaymentFailOnAccount.cls
public class MultiplePaymentFailOnAccount implements Database.Batchable<sObject> , Database.Stateful {
    
public Integer failedPayments = 0;
    
public Database.QueryLocator start(Database.BatchableContext context) 
{
	String query ='Select  Id , Multiple_Payments_Failed__c, NumberOfFailedPayments__c, Name from Account where  NumberOfFailedPayments__c > 2';
	return Database.getQueryLocator(query); 
}
   public void execute(Database.BatchableContext context, List<Account> accounts) 
{
   
        System.debug('am in execute ' + accounts.size());
        //List<Account> AccountToBeUpdated = new List<Account>();
        Account acc = new Account();
        
    	system.debug(' aman ' + accounts.size());
    	if(accounts.size() > 0)
        {
            for(Account payFailCount : accounts)
            {
                //acc.id = payFailCount.id ;
                //System.debug(' payFailCount.id ' +  payFailCount.id);
                //System.debug('aman here again ' + payFailCount.id + ' ' + payFailCount.NumberOfFailedPayments__c + ' ' + payFailCount.Name);
                acc.Multiple_Payments_Failed__c = true;
                //AccountToBeUpdated.add(acc);
                failedPayments += integer.valueOf(payFailCount.NumberOfFailedPayments__c) ;
            }
        }
        Database.SaveResult[] saveUpdateResult = Database.update(accounts); 
        for (Database.SaveResult sr : saveUpdateResult) {
            if (sr.isSuccess()) {
                System.debug('Successfully updated account. Account ID: ' + sr.getId());
            }
            else {              
                for(Database.Error err : sr.getErrors()) {
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Account fields that affected this error: ' + err.getFields());
                }
            }
            
        }
    
}
    public void finish(Database.BatchableContext context) {  
        AsyncApexJob a = [Select Id, Status,ExtendedStatus,NumberOfErrors,     JobItemsProcessed,
                          TotalJobItems, CreatedBy.Email
                          from AsyncApexJob where Id =:context.getJobId()];
        FailedPaymentInfo__mdt failpmnt = new FailedPaymentInfo__mdt();
        failpmnt.RecipientEmail__c = a.CreatedBy.Email;
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {failpmnt.RecipientEmail__c};
            mail.setToAddresses(toAddresses);
        mail.setSubject('Payment status Report ' );
        mail.setPlainTextBody('Today, a total of * ' + failedPayments + '* payments failed ');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    
}