force-app/main/default/objects/Order_Detail__c/Order_Detail__c.object-meta.xml
<CustomObject>
    <description>Details of Orders placed.</description>
    <label>Order Detail</label>
    <nameField>
        <displayFormat>ORD-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Detail__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <description>Employer of the Contact who placed order</description>
    <inlineHelpText>Enter your Employer name</inlineHelpText>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Details</relationshipLabel>
    <relationshipName>Order_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Detail__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <description>Return current date when a new order is created</description>
    <formula>IF( ISPICKVAL( Status__c , &quot;New&quot;),  DATETIMEVALUE(TODAY()) ,null )</formula>
    <inlineHelpText>Current date time is auto populated as and when a new order is placed.</inlineHelpText>
    <label>Order Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TestOrdersAndInvoices.cls
@IsTest
public class TestOrdersAndInvoices {
    
    @testsetup
    public Static void CreateSampleData()
    {
	Account testAcc = new Account(Name = 'testclassAcc');
	insert testAcc;
    
	Order_Detail__c OrdDetail = new Order_Detail__c(Status__c = 'New', Order_Date__c = Date.newInstance(2021, 10, 05), Employer__c = testAcc.id);
    insert OrdDetail;    
    }
    
    @Istest public Static void testassociatedOrders()
    {
        Account account = [Select Id, name from Account where Name = 'testclassAcc'];
        test.startTest();
        OrdersAndInvoices.associatedOrders(account.Id);
        test.stopTest();      
    }
    @Istest public Static void testassociatedInvoices()
    {
        Account account = [Select Id, name from Account where Name = 'testclassAcc'];
        test.startTest();
        OrdersAndInvoices.associatedInvoices(account.Id);
        test.stopTest();      
    }
}