force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>store the details of Payments received for an Invoice/order as per below. There can be 1 or payment records for a single invoice</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Employer1__c.field-meta.xml
<CustomField>
    <fullName>Employer1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employer1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Failure_reason__c.field-meta.xml
<CustomField>
    <fullName>Failure_reason__c</fullName>
    <description>Reason for failure</description>
    <inlineHelpText>Reason for failure</inlineHelpText>
    <label>Failure reason</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>Amount paid by customer</description>
    <inlineHelpText>Amount paid for an order</inlineHelpText>
    <label>Payment Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Date time when the Payment was attempted</description>
    <inlineHelpText>Date time when the Payment was attempted</inlineHelpText>
    <label>Payment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Net Banking</fullName>
            </value>
            <value>
                <fullName>Wallet</fullName>
            </value>
            <value>
                <fullName>UPI</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>failure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Electronic</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountFactory.cls
public class AccountFactory {
    
    public static List<Account> CreateAccounts(Integer NumberOfAccount, String AccountName)
    {
        List<Account> accounts = new List<Account>();
        
        for (integer i=0; i<NumberOfAccount; i++)
        {
            Account account = new Account();
            account.Name = AccountName + i;
            accounts.add(account);
            
        }
        insert accounts;
        return accounts;
    }
    public static List<Payment__c> CreatePayments(List<Account> accounts, Integer NumberOfPaymentPerAccount)
    {
        List<Payment__c> payList = new List<Payment__c>();
        Set<String> AccountIds = new Set<String>();
        for(Account account : accounts)
        {
            AccountIds.add(account.Id);
        }
        for(String aId : AccountIds)
        {
            for(Integer j=0; j<NumberOfPaymentPerAccount; j++){    
                Payment__c payment = new Payment__c(Payment_Amount__c = 0, Payment_Date__c = Date.today(), Type__c = 'External', Payment_Method__c = 'Cash', Status__c = 'Failure', Failure_Reason__c = 'duplicate Currency', Employer1__c = aId);
                payList.add(payment);
            }
        }
        insert payList;
        return payList;
    }
    public static List<Contact> CreateContacts(Integer NumberOfContactPerAccount, String RecordType) 
    {
        List<Contact> conList = new List<Contact>(); 
        
        for(Integer j=0; j<NumberOfContactPerAccount; j++){    
            Contact con = new Contact(FirstName = 'CFS ', LastName = 'CLN ' +j, RecordTypeId =  RecordType);
            if(j>0)
            {
                con.Email = 'newnigashis'   + j + '@gmail.com';
            }
            else 
            {
                con.Email = 'newnigashis@gmail.com';   
            }
            conList.add(con);
            
        }
        return conList;
    }
    public static List<User> CreateUsers(Integer NumberOfUsers) 
    {
        List<User> userList = new List<User>(); 
        
        for(Integer j=0; j<NumberOfUsers; j++){    
            User usr = new User(FirstName = 'UFS ', LastName = 'ULN ' +j);
            if(j>0)
            {
                usr.Email = 'newnigashis'   + j + '@gmail.com';
            }
            else 
            {
                usr.Email = 'newnigashis@gmail.com';   
            }
            userList.add(usr);
            
        }
        return userList;
    }
    
    
}